import type { LeadHydration } from "./close-hydrate";
import type { CloseActivity, CloseEmailThread } from "./close";

export type FileMap = Map<string, string>;

/**
 * Pure function: turn a `LeadHydration` into a map of relative-paths →
 * file content for the per-lead folder.
 *
 * Contract (set 2026-05-05): **raw extraction only**. No summaries, no
 * truncation, no previews. Anything that requires interpretation lives in
 * a separate phase-2 path (`lead-folder-llm.ts`) and is not regenerated by
 * the sweeper.
 *
 * Files written:
 *  - `00_meta.json`         — local sweep envelope + counts + primary identifiers.
 *  - `01_raw_lead.json`     — full raw Close lead object (every custom field, contact, opportunity).
 *  - `02_continuity.jsonl`  — chronological event index, one JSON line per activity.
 *  - `comms/{kind}_{date}_{shortid}.json` — verbatim per-activity payloads (with call transcripts).
 *  - `comms/thread_{date}_{shortid}.json` — verbatim per-email-thread payloads.
 */
export function renderLeadFolder(hydration: LeadHydration): FileMap {
  const out: FileMap = new Map();

  out.set("00_meta.json", renderMetaJson(hydration));
  out.set("01_raw_lead.json", renderLeadJson(hydration));
  out.set("02_continuity.jsonl", renderContinuity(hydration));

  for (const a of allActivities(hydration)) {
    const path = activityFilename(a);
    if (!path) continue;
    out.set(path, JSON.stringify(a, null, 2) + "\n");
  }
  for (const t of hydration.threads) {
    const path = threadFilename(t);
    if (!path) continue;
    out.set(path, JSON.stringify(t, null, 2) + "\n");
  }

  return out;
}

// ───── 00_meta.json ─────────────────────────────────────────────────────────

function renderMetaJson(h: LeadHydration): string {
  const lead = h.lead;
  const primaryContact = lead.contacts?.[0];
  const meta = sortKeysDeep({
    lead_id: lead.id,
    name: lead.display_name ?? lead.name ?? lead.id,
    contact_id: primaryContact?.id ?? null,
    primary_email: primaryContact?.emails?.[0]?.email ?? null,
    primary_phone: primaryContact?.phones?.[0]?.phone ?? null,
    status_id: lead.status_id ?? null,
    status_label: lead.status_label ?? null,
    organization_id: lead.organization_id ?? null,
    user_id: lead.user_id ?? null,
    user_name: lead.user_name ?? null,
    last_sweep_at: h.fetched_at,
    raw_contract_version: 2,
    raw_files: {
      lead: "01_raw_lead.json",
      continuity: "02_continuity.jsonl",
      comms_dir: "comms/",
    },
    counts: {
      activities: h.activity_total,
      calls: h.calls.length,
      emails: h.emails.length,
      smses: h.smses.length,
      whatsapps: h.whatsapps.length,
      meetings: h.meetings.length,
      notes: h.notes.length,
      tasks: h.tasks.length,
      threads: h.threads.length,
      subscriptions: h.subscriptions.length,
    },
  });
  return JSON.stringify(meta, null, 2) + "\n";
}

// ───── 01_raw_lead.json ─────────────────────────────────────────────────────

/**
 * The full raw Close lead object, JSON-serialized with stable key ordering
 * so byte-stability holds across re-runs. Includes every `custom.cf_*`
 * key, every contact (with all phones / emails / addresses), every
 * opportunity, all dates, status_id/label, owner fields, etc.
 */
function renderLeadJson(h: LeadHydration): string {
  const stable = sortKeysDeep(h.lead as unknown as Record<string, unknown>);
  return JSON.stringify(stable, null, 2) + "\n";
}

// ───── 02_continuity.jsonl ──────────────────────────────────────────────────

/**
 * Chronological event index. One JSON object per line, oldest-first.
 * Pure structured fields — no truncation, no preview text. Phase 2 reads
 * this once to build a timeline cheaply, then loads the matching
 * `comms/*.json` only for events it cares about.
 *
 * Each row: { date, kind, direction, activity_id, user_id, contact_id, ref }
 *  - `kind`: lower-case channel ("call", "email", "sms", "meeting", "note", "task")
 *  - `direction`: "inbound" | "outbound" | null (null for note/task/meeting)
 *  - `ref`: relative path to the verbatim per-activity JSON in the same folder
 */
function renderContinuity(h: LeadHydration): string {
  const ordered = allActivities(h)
    .slice()
    .sort((a, b) =>
      (a.date_created ?? "").localeCompare(b.date_created ?? ""),
    );
  const lines: string[] = [];
  for (const a of ordered) {
    const ref = activityFilename(a);
    if (!ref) continue;
    const row = {
      date: a.date_created ?? null,
      kind: kindOf(a) ?? a._type.toLowerCase(),
      direction: a.direction ?? null,
      activity_id: a.id,
      user_id: a.user_id ?? null,
      contact_id: (a as { contact_id?: string }).contact_id ?? null,
      ref,
    };
    lines.push(JSON.stringify(row));
  }
  // Trailing newline for POSIX-friendly diffs; empty file when no activity.
  return lines.length ? lines.join("\n") + "\n" : "";
}

// ───── helpers ──────────────────────────────────────────────────────────────

function allActivities(h: LeadHydration): CloseActivity[] {
  return [
    ...h.calls,
    ...h.emails,
    ...h.smses,
    ...h.whatsapps,
    ...h.meetings,
    ...h.notes,
    ...h.tasks,
    ...h.unknown_activities,
  ];
}

/** Recursively sort object keys so JSON.stringify produces byte-stable output
 *  regardless of property insertion order from Close. Arrays preserve order. */
function sortKeysDeep(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortKeysDeep);
  }
  if (value && typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const sorted: Record<string, unknown> = {};
    for (const k of Object.keys(obj).sort()) {
      sorted[k] = sortKeysDeep(obj[k]);
    }
    return sorted;
  }
  return value;
}

/** `comms/{kind}_{YYYY-MM-DD}_{shortid}.json`. shortid = last 8 chars of
 *  activity id, lowercased. */
export function activityFilename(a: CloseActivity): string | null {
  const kind = kindOf(a);
  if (!kind) return null;
  const date = (a.date_created ?? "").slice(0, 10);
  if (!date) return null;
  const shortid = a.id.slice(-8).toLowerCase();
  return `comms/${kind}_${date}_${shortid}.json`;
}

function kindOf(a: CloseActivity): string | null {
  switch (a._type) {
    case "Call":
      return "call";
    case "Email":
      return "email";
    case "SMS":
      return "sms";
    case "WhatsappMessage":
    case "WhatsAppMessage":
    case "Whatsapp":
    case "WhatsApp":
      return "whatsapp";
    case "Meeting":
      return "meeting";
    case "Note":
      return "note";
    case "Task":
    case "TaskCompleted":
      return "task";
    default:
      return null;
  }
}

function threadFilename(t: CloseEmailThread): string | null {
  const date = (t.date_created ?? "").slice(0, 10);
  if (!date) return null;
  const shortid = t.id.slice(-8).toLowerCase();
  return `comms/thread_${date}_${shortid}.json`;
}

// re-export for tests
export { allActivities as __allActivities };
